In [10]:
import openpyxl
import pandas as pd       # For data handling
import numpy as np        # For numeric calculations

In [11]:


file_path = r"C:\Users\Administrator\Downloads\online_retail_II.xlsx"

# Load both sheets
df1 = pd.read_excel(file_path, sheet_name='Year 2009-2010')
df2 = pd.read_excel(file_path, sheet_name='Year 2010-2011')

# Combine into single dataframe
df = pd.concat([df1, df2], ignore_index=True )
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Check first 5 rows
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [35]:
# Remove zero quantity rows (possible returns)
df = df[df['Quantity'] != 0]

# Drop duplicates
df.drop_duplicates(inplace=True)

# Handle missing CustomerID or Description
df = df.dropna(subset=['Customer ID', 'Description'])
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TransactionID,Revenue,Discount,Cost,Profit,ReturnFlag,RefundAmount,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,489434_85048,83.4,25.008548,66.72,-8.328548,<NA>,<NA>,2009,12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323P,81.0,4.499674,64.80,11.700326,<NA>,<NA>,2009,12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323W,81.0,7.575383,64.80,8.624617,<NA>,<NA>,2009,12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,489434_22041,100.8,16.306728,80.64,3.853272,<NA>,<NA>,2009,12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,489434_21232,30.0,4.934257,24.00,1.065743,<NA>,<NA>,2009,12

In [36]:
df['TransactionID'] = df['Invoice'].astype(str) + '_' + df['StockCode'].astype(str)
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TransactionID,Revenue,Discount,Cost,Profit,ReturnFlag,RefundAmount,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,489434_85048,83.4,25.008548,66.72,-8.328548,<NA>,<NA>,2009,12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323P,81.0,4.499674,64.80,11.700326,<NA>,<NA>,2009,12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323W,81.0,7.575383,64.80,8.624617,<NA>,<NA>,2009,12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,489434_22041,100.8,16.306728,80.64,3.853272,<NA>,<NA>,2009,12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,489434_21232,30.0,4.934257,24.00,1.065743,<NA>,<NA>,2009,12

In [38]:
df['Revenue'] = df['Quantity'] * df['Price']

In [30]:
# Random discount between 0-30% of revenue
df['Discount'] = df['Revenue'] * np.random.uniform(0, 0.3, size=len(df))

In [31]:
# Assume 20% margin (or adjust per category)
df['Cost'] = df['Revenue'] * 0.8
df['Profit'] = df['Revenue'] - df['Cost'] - df['Discount']

In [39]:
# Flag invoices starting with 'C' as returns
df['ReturnFlag'] = df['Invoice'].str.startswith('C').astype('Int64')
df['RefundAmount'] = df['ReturnFlag'] * df['Revenue']
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TransactionID,Revenue,Discount,Cost,Profit,ReturnFlag,RefundAmount,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,489434_85048,83.4,25.008548,66.72,-8.328548,<NA>,<NA>,2009,12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323P,81.0,4.499674,64.80,11.700326,<NA>,<NA>,2009,12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323W,81.0,7.575383,64.80,8.624617,<NA>,<NA>,2009,12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,489434_22041,100.8,16.306728,80.64,3.853272,<NA>,<NA>,2009,12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,489434_21232,30.0,4.934257,24.00,1.065743,<NA>,<NA>,2009,12

In [40]:
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TransactionID,Revenue,Discount,Cost,Profit,ReturnFlag,RefundAmount,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,489434_85048,83.4,25.008548,66.72,-8.328548,<NA>,<NA>,2009,12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323P,81.0,4.499674,64.80,11.700326,<NA>,<NA>,2009,12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323W,81.0,7.575383,64.80,8.624617,<NA>,<NA>,2009,12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,489434_22041,100.8,16.306728,80.64,3.853272,<NA>,<NA>,2009,12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,489434_21232,30.0,4.934257,24.00,1.065743,<NA>,<NA>,2009,12

In [41]:
df.to_csv("OnlineRetail_Cleaned.csv", index=False)
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TransactionID,Revenue,Discount,Cost,Profit,ReturnFlag,RefundAmount,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,489434_85048,83.4,25.008548,66.72,-8.328548,<NA>,<NA>,2009,12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323P,81.0,4.499674,64.80,11.700326,<NA>,<NA>,2009,12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,489434_79323W,81.0,7.575383,64.80,8.624617,<NA>,<NA>,2009,12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,489434_22041,100.8,16.306728,80.64,3.853272,<NA>,<NA>,2009,12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,489434_21232,30.0,4.934257,24.00,1.065743,<NA>,<NA>,2009,12

In [42]:
import os
print(os.getcwd())

C:\Users\Administrator